export const IPC_CHANNELS = {
  settingsGetSummary: 'settings:getSummary',
  settingsSaveOpenRouterKey: 'settings:saveOpenRouterKey',
  settingsValidateOpenRouterKey: 'settings:validateOpenRouterKey',
  settingsSaveOpenAiKey: 'settings:saveOpenAiKey',
  settingsValidateOpenAiKey: 'settings:validateOpenAiKey',
  settingsSaveGeminiKey: 'settings:saveGeminiKey',
  settingsValidateGeminiKey: 'settings:validateGeminiKey',
  settingsSaveAnthropicKey: 'settings:saveAnthropicKey',
  settingsValidateAnthropicKey: 'settings:validateAnthropicKey',
  settingsUpdatePreferences: 'settings:updatePreferences',
  modelsList: 'models:list',
  modelsRefresh: 'models:refresh',
  modelsRefreshProvider: 'models:refreshProvider',
  conversationsList: 'conversations:list',
  conversationsCreate: 'conversations:create',
  conversationsGet: 'conversations:get',
  chatStart: 'chat:start',
  chatAbort: 'chat:abort',
  chatEvent: 'chat:event'
} as const;
